### ISSUE TITLE
Cannot install telegram (staging branch) on arch via docker install

### ISSUE THREAD

**Issue by LeRatGondin** [mgilangjanuar/teledrive#391]
When I run ./install.docker.sh there aren't any error , but the teledrive app is not lunched and when I do docker compose up I have this error 
```
docker-teledrive-1  | Error: P1000: Authentication failed against database server at `db`, the provided database credentials for `postgres` are not valid.
```
and i tried almost everything i changed the docker-compose.yml I changed the docker install the .env I removed all docker images and container but nothing worked
![image](https://user-images.githubusercontent.com/44407018/178162348-2e38b00a-4797-4a70-8e80-3072e13adce8.png)

and somethimes the error change to 
```
Error: P1013: The provided database string is invalid. invalid port number in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.
```
for no reasons

I'm on Linux archlinux 5.18.9-arch1-1
all my packages are updated and I installed the "working branch"  with the hex encrypt

**Comment by gmendezm** [comment]
I got this error. I solved it changing the password, removing any special character.

If you want to use special characters you need to scape them

What is your URL database format?

**Comment by gorskii** [comment]
After you fix invalid postgres credentials, caused by this [faulty password generator](https://github.com/mgilangjanuar/teledrive/blob/6c7ef8fd9e7d2e5faba917569e08856a8b402f87/install.docker.sh#L24), you need to remove postgres data volume before you run `install.docker.sh` or recreate teledrive container, so postgres could initialize db using correct credentials

```
docker volume rm docker_teledrive_data
```

Postgres image skips its `initdb` step if `PGDATA` directory is not empty
